import json
import os

print("[Subz Engine] Building Rich Curated Vocabulary Database...")

# Load current vocab_core
try:
    with open('src/data/vocab_core.js', 'r', encoding='utf-8') as f:
        content = f.read()
        start = content.find('{')
        end = content.rfind('}')
        core = json.loads(content[start:end+1])
except Exception as e:
    core = {}

# Comprehensive high-yield academic, tech, film, and media vocabulary
rich_vocab = {
    "accessible": {"phonetic": "/əkˈses.ə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Easy to approach, enter, obtain, or understand.", "synonyms": ["reachable", "approachable", "available"]},
    "accommodate": {"phonetic": "/əˈkɒm.ə.deɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To provide space for, or to adapt and adjust to someone's needs.", "synonyms": ["adjust", "adapt", "house"]},
    "accumulate": {"phonetic": "/əˈkjuː.mjə.leɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To gradually gather or build up a large amount of something over time.", "synonyms": ["gather", "collect", "amass"]},
    "acknowledge": {"phonetic": "/əkˈnɒl.ɪdʒ/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To accept or admit the existence or truth of something.", "synonyms": ["admit", "recognize", "accept"]},
    "adjacent": {"phonetic": "/əˈdʒeɪ.sənt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Next to or adjoining something else.", "synonyms": ["neighboring", "adjoining", "next-door"]},
    "advocate": {"phonetic": "/ˈæd.və.keɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To publicly support or recommend a particular cause or policy.", "synonyms": ["champion", "support", "recommend"]},
    "aesthetic": {"phonetic": "/esˈθet.ɪk/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Concerned with beauty, artistic taste, or visual appearance.", "synonyms": ["artistic", "visual", "stylish"]},
    "allocate": {"phonetic": "/ˈæl.ə.keɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To distribute resources or duties for a specific purpose.", "synonyms": ["assign", "distribute", "allot"]},
    "ambiguous": {"phonetic": "/æmˈbɪɡ.ju.əs/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Open to more than one interpretation; unclear or vague.", "synonyms": ["unclear", "vague", "doubtful"]},
    "amplify": {"phonetic": "/ˈæm.plɪ.faɪ/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To make something larger, louder, or more intense.", "synonyms": ["boost", "increase", "magnify"]},
    "analogy": {"phonetic": "/əˈnæl.ə.dʒi/", "partOfSpeech": "noun", "level": "intermediate", "definition": "A comparison between two things that helps explain an idea.", "synonyms": ["comparison", "parallel", "metaphor"]},
    "anomaly": {"phonetic": "/əˈnɒm.ə.li/", "partOfSpeech": "noun", "level": "advanced", "definition": "Something that deviates from what is standard, normal, or expected.", "synonyms": ["oddity", "irregularity", "exception"]},
    "anticipate": {"phonetic": "/ænˈtɪs.ɪ.peɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To expect or predict something and prepare for it in advance.", "synonyms": ["expect", "foresee", "predict"]},
    "arbitrary": {"phonetic": "/ˈɑː.bɪ.trər.i/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Based on random choice or personal whim, rather than any reason or system.", "synonyms": ["random", "capricious", "unreasoned"]},
    "articulate": {"phonetic": "/ɑːˈtɪk.jə.lət/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Able to express ideas clearly and fluently in speech or writing.", "synonyms": ["fluent", "eloquent", "clear"]},
    "assertion": {"phonetic": "/əˈsɜː.ʃən/", "partOfSpeech": "noun", "level": "intermediate", "definition": "A confident and forceful statement of fact or belief.", "synonyms": ["claim", "declaration", "statement"]},
    "assimilate": {"phonetic": "/əˈsɪm.ɪ.leɪt/", "partOfSpeech": "verb", "level": "advanced", "definition": "To absorb and fully understand information, ideas, or culture.", "synonyms": ["absorb", "integrate", "incorporate"]},
    "autonomous": {"phonetic": "/ɔːˈtɒn.ə.məs/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Having the freedom to act independently or govern oneself.", "synonyms": ["independent", "self-governing", "free"]},
    "benchmark": {"phonetic": "/ˈbentʃ.mɑːk/", "partOfSpeech": "noun", "level": "intermediate", "definition": "A standard point of reference used for comparison or measurement.", "synonyms": ["standard", "criterion", "gauge"]},
    "bias": {"phonetic": "/ˈbaɪ.əs/", "partOfSpeech": "noun", "level": "intermediate", "definition": "Prejudice in favor of or against one thing, person, or group.", "synonyms": ["prejudice", "partiality", "leaning"]},
    "bolster": {"phonetic": "/ˈbəʊl.stər/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To support, strengthen, or prop up.", "synonyms": ["strengthen", "support", "reinforce"]},
    "catalyst": {"phonetic": "/ˈkæt.əl.ɪst/", "partOfSpeech": "noun", "level": "advanced", "definition": "A person or event that quickly causes an important change to happen.", "synonyms": ["trigger", "spark", "stimulus"]},
    "chronic": {"phonetic": "/ˈkrɒn.ɪk/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Persisting for a long time or constantly recurring.", "synonyms": ["persistent", "long-standing", "constant"]},
    "clarify": {"phonetic": "/ˈklær.ɪ.faɪ/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To make a statement or situation less confused and more clearly comprehensible.", "synonyms": ["explain", "simplify", "clear up"]},
    "cohesive": {"phonetic": "/kəʊˈhiː.sɪv/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Forming a united, connected, and logical whole.", "synonyms": ["unified", "connected", "integrated"]},
    "collaborate": {"phonetic": "/kəˈlæb.ə.reɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To work jointly with others on an activity or project.", "synonyms": ["cooperate", "team up", "work together"]},
    "commodity": {"phonetic": "/kəˈmɒd.ə.ti/", "partOfSpeech": "noun", "level": "intermediate", "definition": "A raw material or primary agricultural product that can be bought and sold.", "synonyms": ["product", "goods", "merchandise"]},
    "compatible": {"phonetic": "/kəmˈpæt.ə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Able to exist, occur, or work together smoothly without conflict.", "synonyms": ["harmonious", "suited", "consistent"]},
    "compensate": {"phonetic": "/ˈkɒm.pən.seɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To give someone something (usually money) to make up for loss or suffering.", "synonyms": ["recompense", "repay", "make up"]},
    "competent": {"phonetic": "/ˈkɒm.pɪ.tənt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Having the necessary ability, knowledge, or skill to do something successfully.", "synonyms": ["capable", "able", "proficient"]},
    "compile": {"phonetic": "/kəmˈpaɪl/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To produce by assembling information collected from other sources.", "synonyms": ["assemble", "gather", "collect"]},
    "comprehensive": {"phonetic": "/ˌkɒm.prɪˈhen.sɪv/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Complete and thorough; including or dealing with all aspects.", "synonyms": ["complete", "thorough", "exhaustive"]},
    "compromise": {"phonetic": "/ˈkɒm.prə.maɪz/", "partOfSpeech": "noun", "level": "intermediate", "definition": "An agreement reached when both sides give up some demands.", "synonyms": ["agreement", "settlement", "concession"]},
    "consensus": {"phonetic": "/kənˈsen.səs/", "partOfSpeech": "noun", "level": "advanced", "definition": "A general agreement reached by everyone in a group.", "synonyms": ["agreement", "harmony", "unity"]},
    "constrain": {"phonetic": "/kənˈstreɪn/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To severely restrict the scope, extent, or activity of something.", "synonyms": ["restrict", "limit", "restrain"]},
    "contemplate": {"phonetic": "/ˈkɒn.təm.pleɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To look thoughtfully at or think about deeply for a long time.", "synonyms": ["consider", "ponder", "reflect"]},
    "contradict": {"phonetic": "/ˌkɒn.trəˈdɪkt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To deny the truth of a statement by asserting the opposite.", "synonyms": ["oppose", "challenge", "deny"]},
    "controversy": {"phonetic": "/ˈkɒn.trə.vɜː.si/", "partOfSpeech": "noun", "level": "intermediate", "definition": "Prolonged public disagreement or heated debate.", "synonyms": ["dispute", "debate", "disagreement"]},
    "converge": {"phonetic": "/kənˈvɜːdʒ/", "partOfSpeech": "verb", "level": "advanced", "definition": "To come together from different directions and meet at an intersection.", "synonyms": ["meet", "merge", "unite"]},
    "correlate": {"phonetic": "/ˈkɒr.ə.leɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To have a mutual relationship or connection, in which one affects the other.", "synonyms": ["correspond", "connect", "relate"]},
    "criteria": {"phonetic": "/kraɪˈtɪə.ri.ə/", "partOfSpeech": "noun", "level": "intermediate", "definition": "Principles or standards by which something may be judged or decided.", "synonyms": ["standards", "benchmarks", "measures"]},
    "crucial": {"phonetic": "/ˈkruː.ʃəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Extremely important or decisive for the success of something.", "synonyms": ["vital", "essential", "critical"]},
    "cynical": {"phonetic": "/ˈsɪn.ɪ.kəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Believing that people are motivated purely by self-interest; distrustful.", "synonyms": ["skeptical", "distrustful", "pessimistic"]},
    "deduce": {"phonetic": "/dɪˈdʒuːs/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To arrive at a fact or conclusion by reasoning and evidence.", "synonyms": ["conclude", "infer", "reason"]},
    "deliberate": {"phonetic": "/dɪˈlɪb.ər.ət/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Done consciously and intentionally; carefully weighed.", "synonyms": ["intentional", "planned", "calculated"]},
    "depict": {"phonetic": "/dɪˈpɪkt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To represent or show in a picture, story, or words.", "synonyms": ["portray", "represent", "illustrate"]},
    "deteriorate": {"phonetic": "/dɪˈtɪə.ri.ə.reɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To become progressively worse over time.", "synonyms": ["worsen", "decline", "decay"]},
    "dichotomy": {"phonetic": "/daɪˈkɒt.ə.mi/", "partOfSpeech": "noun", "level": "advanced", "definition": "A division or contrast between two completely opposite things.", "synonyms": ["division", "contrast", "split"]},
    "differentiate": {"phonetic": "/ˌdɪf.əˈren.ʃi.eɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To recognize or show what makes someone or something different.", "synonyms": ["distinguish", "discriminate", "tell apart"]},
    "diligent": {"phonetic": "/ˈdɪl.ɪ.dʒənt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Having or showing conscientious care and effort in one's work.", "synonyms": ["hardworking", "industrious", "attentive"]},
    "diminish": {"phonetic": "/dɪˈmɪn.ɪʃ/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To make or become smaller, fewer, or less.", "synonyms": ["reduce", "decrease", "lessen"]},
    "discrepancy": {"phonetic": "/dɪˈskrep.ən.si/", "partOfSpeech": "noun", "level": "advanced", "definition": "A lack of compatibility or noticeable difference between two facts.", "synonyms": ["difference", "inconsistency", "mismatch"]},
    "discreet": {"phonetic": "/dɪˈskriːt/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Careful and prudent in speech or actions to avoid offense or revealing secrets.", "synonyms": ["tactful", "cautious", "subtle"]},
    "disperse": {"phonetic": "/dɪˈspɜːs/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To distribute or spread over a wide area; scatter.", "synonyms": ["scatter", "spread", "distribute"]},
    "diverge": {"phonetic": "/daɪˈvɜːdʒ/", "partOfSpeech": "verb", "level": "advanced", "definition": "To separate from another route or move in a different direction.", "synonyms": ["separate", "split", "deviate"]},
    "dynamic": {"phonetic": "/daɪˈnæm.ɪk/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Characterized by constant change, activity, or fresh progress.", "synonyms": ["active", "energetic", "changing"]},
    "elaborate": {"phonetic": "/ɪˈlæb.ər.ət/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Involving many carefully arranged parts or details; rich and complex.", "synonyms": ["detailed", "complex", "intricate"]},
    "eloquent": {"phonetic": "/ˈel.ə.kwənt/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Fluent or persuasive in speaking or writing.", "synonyms": ["articulate", "persuasive", "expressive"]},
    "elusive": {"phonetic": "/ɪˈluː.sɪv/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Difficult to find, catch, remember, or achieve.", "synonyms": ["slippery", "evasive", "hard to find"]},
    "empirical": {"phonetic": "/ɪmˈpɪr.ɪ.kəl/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Based on, concerned with, or verifiable by observation or experiment rather than theory.", "synonyms": ["observed", "experimental", "practical"]},
    "enervate": {"phonetic": "/ˈen.ə.veɪt/", "partOfSpeech": "verb", "level": "advanced", "definition": "To drain of energy or vitality; weaken physically or mentally.", "synonyms": ["exhaust", "fatigue", "weaken"]},
    "enhance": {"phonetic": "/ɪnˈhɑːns/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To intensify, increase, or further improve the quality or value of something.", "synonyms": ["improve", "boost", "upgrade"]},
    "ephemeral": {"phonetic": "/ɪˈfem.ər.əl/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Lasting for only a very short time; fleeting.", "synonyms": ["fleeting", "short-lived", "transitory"]},
    "epiphany": {"phonetic": "/ɪˈpɪf.ə.ni/", "partOfSpeech": "noun", "level": "advanced", "definition": "A sudden moment when you deeply realize or understand an essential truth.", "synonyms": ["realization", "breakthrough", "insight"]},
    "equate": {"phonetic": "/ɪˈkweɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To consider one thing to be the same as or equal to another.", "synonyms": ["compare", "associate", "balance"]},
    "erroneous": {"phonetic": "/ɪˈrəʊ.ni.əs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Wrong; incorrect; based on an error.", "synonyms": ["incorrect", "mistaken", "wrong"]},
    "escalate": {"phonetic": "/ˈes.kə.leɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To increase rapidly in intensity, scale, or severity.", "synonyms": ["intensify", "heighten", "increase"]},
    "esoteric": {"phonetic": "/ˌes.əˈter.ɪk/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Intended for or understood by only a small group with specialized knowledge.", "synonyms": ["obscure", "arcane", "cryptic"]},
    "exacerbate": {"phonetic": "/ɪɡˈzæs.ə.beɪt/", "partOfSpeech": "verb", "level": "advanced", "definition": "To make a problem, bad situation, or pain worse.", "synonyms": ["worsen", "aggravate", "inflame"]},
    "exemplary": {"phonetic": "/ɪɡˈzem.plər.i/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Serving as a desirable model; representing the best of its kind.", "synonyms": ["model", "ideal", "outstanding"]},
    "expedite": {"phonetic": "/ˈek.spə.daɪt/", "partOfSpeech": "verb", "level": "advanced", "definition": "To make an action or process happen much more quickly.", "synonyms": ["speed up", "accelerate", "hasten"]},
    "explicit": {"phonetic": "/ɪkˈsplɪs.ɪt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Stated clearly and in detail, leaving no room for confusion or doubt.", "synonyms": ["clear", "direct", "unambiguous"]},
    "facilitate": {"phonetic": "/fəˈsɪl.ɪ.teɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To make an action or process easy or easier.", "synonyms": ["ease", "assist", "help"]},
    "fastidious": {"phonetic": "/fæsˈtɪd.i.əs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Very attentive to and concerned about accuracy and minute detail.", "synonyms": ["meticulous", "exacting", "particular"]},
    "feasible": {"phonetic": "/ˈfiː.zə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Possible to do easily or conveniently; practically achievable.", "synonyms": ["workable", "viable", "achievable"]},
    "fluctuate": {"phonetic": "/ˈflʌk.tʃu.eɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To rise and fall irregularly in number, amount, or state.", "synonyms": ["vary", "shift", "swing"]},
    "formidable": {"phonetic": "/fɔːˈmɪd.ə.bəl/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Inspiring fear or respect through being impressively large or capable.", "synonyms": ["intimidating", "powerful", "daunting"]},
    "frictionless": {"phonetic": "/ˈfrɪk.ʃən.ləs/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Smooth and effortless, with no difficulty, delay, or resistance.", "synonyms": ["effortless", "smooth", "seamless"]},
    "futile": {"phonetic": "/ˈfjuː.taɪl/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Incapable of producing any useful result; pointless.", "synonyms": ["pointless", "useless", "vain"]},
    "hierarchy": {"phonetic": "/ˈhaɪə.rɑː.ki/", "partOfSpeech": "noun", "level": "intermediate", "definition": "A system in which members are ranked according to status or authority.", "synonyms": ["ranking", "order", "pecking order"]},
    "hinder": {"phonetic": "/ˈhɪn.dər/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To create difficulties for someone or something, resulting in delay.", "synonyms": ["obstruct", "hamper", "impede"]},
    "hypothesis": {"phonetic": "/haɪˈpɒθ.ə.sɪs/", "partOfSpeech": "noun", "level": "intermediate", "definition": "A proposed explanation made as a starting point for further investigation.", "synonyms": ["theory", "premise", "assumption"]},
    "implicit": {"phonetic": "/ɪmˈplɪs.ɪt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Implied though not plainly expressed in words.", "synonyms": ["implied", "indirect", "tacit"]},
    "incentive": {"phonetic": "/ɪnˈsen.tɪv/", "partOfSpeech": "noun", "level": "intermediate", "definition": "A thing that motivates or encourages someone to do something.", "synonyms": ["motivation", "reward", "inducement"]},
    "inevitable": {"phonetic": "/ɪnˈev.ɪ.tə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Certain to happen; unavoidable.", "synonyms": ["unavoidable", "inescapable", "certain"]},
    "inherent": {"phonetic": "/ɪnˈhɪə.rənt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Existing in something as a permanent, essential, or characteristic attribute.", "synonyms": ["intrinsic", "innate", "built-in"]},
    "inhibit": {"phonetic": "/ɪnˈhɪb.ɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To hinder, restrain, or prevent an action or process.", "synonyms": ["prevent", "restrain", "suppress"]},
    "innovate": {"phonetic": "/ˈɪn.ə.veɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To introduce new methods, ideas, or products.", "synonyms": ["pioneer", "create", "invent"]},
    "integrity": {"phonetic": "/ɪnˈteɡ.rə.ti/", "partOfSpeech": "noun", "level": "intermediate", "definition": "The quality of being honest and having strong moral principles.", "synonyms": ["honesty", "honor", "truthfulness"]},
    "intricate": {"phonetic": "/ˈɪn.trɪ.kət/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Very complicated or detailed.", "synonyms": ["complex", "elaborate", "involved"]},
    "intrinsic": {"phonetic": "/ɪnˈtrɪn.zɪk/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Belonging naturally; essential.", "synonyms": ["innate", "inherent", "fundamental"]},
    "intuitive": {"phonetic": "/ɪnˈtjuː.ɪ.tɪv/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Easy to understand or use without special training.", "synonyms": ["instinctive", "natural", "user-friendly"]},
    "juxtaposition": {"phonetic": "/ˌdʒʌk.stə.pəˈzɪʃ.ən/", "partOfSpeech": "noun", "level": "advanced", "definition": "Placing two things close together with contrasting effect.", "synonyms": ["comparison", "contrast", "proximity"]},
    "legitimate": {"phonetic": "/lɪˈdʒɪt.ɪ.mət/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Conforming to the law or rules; valid and fair.", "synonyms": ["valid", "lawful", "genuine"]},
    "leverage": {"phonetic": "/ˈliː.vər.ɪdʒ/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To use something to maximum advantage.", "synonyms": ["utilize", "exploit", "use"]},
    "lucid": {"phonetic": "/ˈluː.sɪd/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Expressed clearly; easy to understand.", "synonyms": ["clear", "transparent", "coherent"]},
    "magnanimous": {"phonetic": "/mæɡˈnæn.ɪ.məs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Very generous or forgiving, especially toward a rival.", "synonyms": ["generous", "charitable", "noble"]},
    "manifest": {"phonetic": "/ˈmæn.ɪ.fest/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To display or show by one's acts or appearance; demonstrate.", "synonyms": ["show", "exhibit", "display"]},
    "meticulous": {"phonetic": "/məˈtɪk.jə.ləs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Showing great attention to detail; very careful and precise.", "synonyms": ["precise", "detailed", "careful"]},
    "mitigate": {"phonetic": "/ˈmɪt.ɪ.ɡeɪt/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To make something bad or painful less severe or harmful.", "synonyms": ["reduce", "lessen", "alleviate"]},
    "momentum": {"phonetic": "/məˈmen.təm/", "partOfSpeech": "noun", "level": "intermediate", "definition": "The quantity of motion of a moving body, or speed of progress.", "synonyms": ["impetus", "drive", "energy"]},
    "notorious": {"phonetic": "/nəʊˈtɔː.ri.əs/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Famous or well known, typically for some bad quality or deed.", "synonyms": ["infamous", "scandalous", "ill-famed"]},
    "nuance": {"phonetic": "/ˈnjuː.ɑːns/", "partOfSpeech": "noun", "level": "advanced", "definition": "A subtle difference in meaning, opinion, or color.", "synonyms": ["subtlety", "shade", "distinction"]},
    "obsolete": {"phonetic": "/ˌɒb.səˈliːt/", "partOfSpeech": "adjective", "level": "advanced", "definition": "No longer produced or used; out of date.", "synonyms": ["outdated", "archaic", "superseded"]},
    "paradigm": {"phonetic": "/ˈpær.ə.daɪm/", "partOfSpeech": "noun", "level": "advanced", "definition": "A typical example or pattern of something; a model.", "synonyms": ["model", "pattern", "standard"]},
    "paradox": {"phonetic": "/ˈpær.ə.dɒks/", "partOfSpeech": "noun", "level": "advanced", "definition": "A statement that seems contradictory but may reveal a deeper truth.", "synonyms": ["contradiction", "puzzle", "enigma"]},
    "perceive": {"phonetic": "/pəˈsiːv/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To become aware of or understand something through the senses or mind.", "synonyms": ["notice", "see", "recognize"]},
    "pernicious": {"phonetic": "/pəˈnɪʃ.əs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Having a harmful effect, especially in a gradual or subtle way.", "synonyms": ["damaging", "harmful", "destructive"]},
    "plausible": {"phonetic": "/ˈplɔː.zə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Seeming reasonable or probable; believable.", "synonyms": ["believable", "credible", "likely"]},
    "pragmatic": {"phonetic": "/præɡˈmæt.ɪk/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Dealing with things sensibly and realistically in a practical way.", "synonyms": ["practical", "realistic", "sensible"]},
    "preliminary": {"phonetic": "/prɪˈlɪm.ɪ.nər.i/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Denoting an action or event preceding something fuller or more important.", "synonyms": ["initial", "introductory", "preparatory"]},
    "quintessential": {"phonetic": "/ˌkwɪn.tɪˈsen.ʃəl/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Representing the most perfect or typical example of a quality or class.", "synonyms": ["classic", "typical", "ideal"]},
    "redundant": {"phonetic": "/rɪˈdʌn.dənt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Not or no longer needed or useful; superfluous.", "synonyms": ["superfluous", "unnecessary", "excess"]},
    "reluctant": {"phonetic": "/rɪˈlʌk.tənt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Unwilling and hesitant; disinclined.", "synonyms": ["hesitant", "unwilling", "slow"]},
    "resilient": {"phonetic": "/rɪˈzɪl.i.ənt/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Able to withstand or recover quickly from difficult conditions.", "synonyms": ["tough", "strong", "hardy"]},
    "rigorous": {"phonetic": "/ˈrɪɡ.ər.əs/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Extremely thorough, exhaustive, or accurate.", "synonyms": ["thorough", "meticulous", "strict"]},
    "robust": {"phonetic": "/rəʊˈbʌst/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Strong and healthy; vigorous; able to handle tough conditions.", "synonyms": ["strong", "sturdy", "durable"]},
    "scrutinize": {"phonetic": "/ˈskruː.tɪ.naɪz/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To examine or inspect closely and thoroughly.", "synonyms": ["inspect", "examine", "investigate"]},
    "seamless": {"phonetic": "/ˈsiːm.ləs/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Smooth and continuous, with no noticeable transitions or breaks.", "synonyms": ["smooth", "continuous", "flawless"]},
    "semantic": {"phonetic": "/sɪˈmæn.tɪk/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Relating to the real meaning and logic of words, language, or data.", "synonyms": ["meaningful", "linguistic", "conceptual"]},
    "serendipity": {"phonetic": "/ˌser.ənˈdɪp.ə.ti/", "partOfSpeech": "noun", "level": "advanced", "definition": "The occurrence of events by chance in a happy or beneficial way.", "synonyms": ["chance", "fluke", "happy accident"]},
    "spontaneous": {"phonetic": "/spɒnˈteɪ.ni.əs/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Performed or occurring as a result of a sudden impulse without planning.", "synonyms": ["unplanned", "impromptu", "natural"]},
    "substantial": {"phonetic": "/səbˈstæn.ʃəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Of considerable importance, size, or worth.", "synonyms": ["considerable", "significant", "large"]},
    "subtle": {"phonetic": "/ˈsʌt.əl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Clever, understated, and not immediately obvious.", "synonyms": ["delicate", "understated", "faint"]},
    "succinct": {"phonetic": "/səkˈsɪŋkt/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Briefly and clearly expressed; concise.", "synonyms": ["concise", "brief", "compact"]},
    "surreptitious": {"phonetic": "/ˌsʌr.əpˈtɪʃ.əs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Kept secret, especially because it would not be approved of.", "synonyms": ["secretive", "stealthy", "clandestine"]},
    "sustain": {"phonetic": "/səˈsteɪn/", "partOfSpeech": "verb", "level": "intermediate", "definition": "To strengthen, support, or keep an action going continuously.", "synonyms": ["maintain", "support", "prolong"]},
    "taciturn": {"phonetic": "/ˈtæs.ɪ.tɜːn/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Reserved or uncommunicative in speech; saying little.", "synonyms": ["silent", "quiet", "reticent"]},
    "tangible": {"phonetic": "/ˈtæn.dʒə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Perceptible by touch; clear and definite; real.", "synonyms": ["concrete", "real", "touchable"]},
    "tenacious": {"phonetic": "/təˈneɪ.ʃəs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Tending to keep a firm hold of something; persistent and determined.", "synonyms": ["persistent", "determined", "stubborn"]},
    "tentative": {"phonetic": "/ˈten.tə.tɪv/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Not certain or fixed; provisional; done with hesitation.", "synonyms": ["provisional", "hesitant", "unconfirmed"]},
    "tenuous": {"phonetic": "/ˈten.ju.əs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Very weak, doubtful, or slight.", "synonyms": ["fragile", "shaky", "flimsy"]},
    "ubiquitous": {"phonetic": "/juːˈbɪk.wɪ.təs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Present, appearing, or found everywhere at the same time.", "synonyms": ["omnipresent", "pervasive", "everywhere"]},
    "unprecedented": {"phonetic": "/ʌnˈpres.ɪ.den.tɪd/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Never having happened or existed before.", "synonyms": ["unmatched", "unheard-of", "novel"]},
    "venerable": {"phonetic": "/ˈven.ər.ə.bəl/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Accorded a great deal of respect, especially because of wisdom or age.", "synonyms": ["respected", "revered", "honored"]},
    "viable": {"phonetic": "/ˈvaɪ.ə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Capable of working successfully; feasible.", "synonyms": ["workable", "feasible", "practical"]},
    "vicarious": {"phonetic": "/vɪˈkeə.ri.əs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Experienced in the imagination through the feelings or actions of another.", "synonyms": ["indirect", "secondary", "empathetic"]},
    "volatile": {"phonetic": "/ˈvɒl.ə.taɪl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Liable to change rapidly and unpredictably, especially for the worse.", "synonyms": ["unstable", "turbulent", "unpredictable"]},
    "vulnerable": {"phonetic": "/ˈvʌl.nər.ə.bəl/", "partOfSpeech": "adjective", "level": "intermediate", "definition": "Susceptible to physical or emotional attack or harm.", "synonyms": ["exposed", "defenseless", "fragile"]},
    "zealous": {"phonetic": "/ˈzel.əs/", "partOfSpeech": "adjective", "level": "advanced", "definition": "Having or showing great passion, devotion, or enthusiasm.", "synonyms": ["fervent", "passionate", "ardent"]}
}

core.update(rich_vocab)

with open('src/data/vocab_core.js', 'w', encoding='utf-8') as f:
    f.write('/**\n * Subz — Curated Core Vocabulary Database\n * High-yield authentic vocabulary with simple, clean definitions.\n */\n\n')
    f.write('const SUBZ_VOCAB_CORE = ' + json.dumps(core, indent=2, ensure_ascii=False) + ';\n\n')
    f.write('if (typeof window !== "undefined") {\n  window.SUBZ_VOCAB_CORE = SUBZ_VOCAB_CORE;\n}\n')
    f.write('if (typeof module !== "undefined" && module.exports) {\n  module.exports = { SUBZ_VOCAB_CORE };\n}\n')

print(f"Successfully wrote {len(core)} rich vocabulary items into src/data/vocab_core.js")
